Make client authentication configurable
bitnami/bitnami-docker-kafka pull request #142
Opened 2021-01-27 12:29 UTC by hugo19941994

**Description of the change**

This change adds a new environment variable (`KAFKA_CFG_SSL_CLIENT_AUTH`) which allows users to choose whether to enable client authentication or not, while keeping encryption enabled. This new environment variable maps 1 to 1 with Kafka's `ssl.client.auth`. As such, the same values can be used:

* `none`: Disables client authentication completely
* `requested`: Enables client authentication without making it mandatory
* `required`: Enables client authentication for all client connections (default value to keep backwards compatibility)

If an invalid value is used an error message is logged indicating which values should be used.

To maintain backwards compatibility, `required` is the default value (which was previously hardcoded).

**Benefits**

Adds flexibility when deciding how to secure the Kafka cluster. While mTLS provides both encryption and authentication, in some instances it can be a hassle managing certificates for clients. With this option brokers can be deployed with TLS enabled, which provides encryption without the burden of generating client certificates.

**Possible drawbacks**

**Applicable issues**

**Additional information**

[Link to Kafka ssl.client.auth docs](https://kafka.apache.org/documentation/#connectconfigs_ssl.client.auth)

2021-01-28 13:08 UTC, migruiz4 requested changes
Thank you very much for your contribution! Could you please have a look at the suggestion I added?

2021-01-28 13:08 UTC, migruiz4 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    fi
To maintain consistency with other Bitnami images, could you please use instead the function `check_multi_values()`?

```sh
check_multi_value "KAFKA_CFG_SSL_CLIENT_AUTH" "none requested required"
```

The function hasn't been added to this file yet, could you please add it using this file as a reference?
https://github.com/bitnami/bitnami-docker-joomla/blob/24f9ab84f7e50ff08fc22e6bd5f96d24a56b7dfd/3/debian-10/rootfs/opt/bitnami/scripts/libjoomla.sh#L47-L51

2021-01-28 17:14 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    fi
Changed

2021-01-29 14:54 UTC, migruiz4 approved these changes
Looks good to me, thanks!

2021-01-29 16:01 UTC, juan131 requested changes
Thanks so much for your PR! Please check my comments.

2021-01-29 16:01 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    check_multi_value "KAFKA_CFG_SSL_CLIENT_AUTH" "none requested required"
You're treating the 3 words as a single string:
```suggestion
    check_multi_value "KAFKA_CFG_SSL_CLIENT_AUTH" "none" "requested" "required"
```

2021-01-29 18:51 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +export KAFKA_CFG_SSL_CLIENT_AUTH="${KAFKA_CFG_SSL_CLIENT_AUTH:-required}"
Done

2021-02-01 08:05 UTC, juan131 approved these changes
Thanks for implementing the suggestions! LGTM

2021-02-01 08:16 UTC, juan131 commented
(sending your PR for internal review, I'll keep you updated)

2021-02-01 09:44 UTC, juan131 commented
PR accepted in internal review, merging your PR!
What's next? A new image revision will be released including your changes. I'll keep you updated once it's released.

2021-02-01 09:44 UTC, merged

2021-02-01 10:17 UTC, juan131 commented
@hugo19941994 we just released the revision **2.7.0-debian-10-r40** including your changes. Please give it a try when you have a chance.