Add support for PEM certificate files
bitnami/bitnami-docker-kafka pull request #143
Opened 2021-01-27 14:44 UTC by hugo19941994

**Description of the change**

Adds support for truststore and keystore certificates in PEM format (in addition to JKS).

No new configuration parameters have been added. To use PEM certs they must be placed and called in a specific way (in a similar fashion to how JKS must be configured in the container):

* `kafka.pem`: public certificate (equivalent to part of the JKS keystore)
* `kafka.key`: private key (equivalent to part of the JKS keystore)
* `ca-cert`: public CA certificate (equivalent to the JKS truststore)

The private key can be encrypted. Set the password with the KAFKA_CERTIFICATE_PASSWORD environment variable.

The keys and certificates will be stored as a multi-line string in the
properties files. e.g.:

```
ssl.truststore.certificates=-----BEGIN CERTIFICATE----- \
MIIDrzCCApegAwIBAgIUYFLNWpsO1I5AbYxSfG05qXZaBK0wDQYJKoZIhvcNAQEL \
BQAwZzELMAkGA1UEBhMCTk4xCzAJBgNVBAgMAk5OMQswCQYDVQQHDAJOTjELMAkG \
A1UECgwCTk4xCzAJBgNVBAsMAk5OMQwwCgYDVQQDDANzbWQxFjAUBgkqhkiG9w0B \
CQEWB2hmc0BzbWQwHhcNMjEwMTI1MTE0OTA5WhcNNDgwNjEyMTE0OTA5WjBnMQsw \
CQYDVQQGEwJOTjELMAkGA1UECAwCTk4xCzAJBgNVBAcMAk5OMQswCQYDVQQKDAJO \
TjELMAkGA1UECwwCTk4xDDAKBgNVBAMMA3NtZDEWMBQGCSqGSIb3DQEJARYHaGZz \
QHNtZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJbwktqe5JiwvtRB \
ka0E3H295GJDHVmLKpXqzwg+cAqjrE0SYE+X4rs9jgztXYsYJOtAqBB7nsNOV1Ly \
O8jSzT/0UnUPx7KpWNRzmTvSpRaCH9HL7NthSuENXLcPYFd2BCSL7NBCszmGVRhw \
TJCOHjbIez9kK3qXHOcnsuXsCaSuiipr/JNkvkgOyamm7qBGOHCoRvKA9WFoKqDh \
12z497nwHtPyZIYeQjBOi++pmusMQZt7y5N5zHDIeg1CD7Jw0eCcVzkSep5LL/7t \
Fuvr9+pIUpo/pdINMrpXV4c+ZYdd6RHvvq94jJQS3vl/G088peCKtER288otxdZZ \
eFOEAX0CAwEAAaNTMFEwHQYDVR0OBBYEFLi4eQDLbB5+hKAo6H3aIp9NAVjhMB8G \
A1UdIwQYMBaAFLi4eQDLbB5+hKAo6H3aIp9NAVjhMA8GA1UdEwEB/wQFMAMBAf8w \
DQYJKoZIhvcNAQELBQADggEBAG0XF9HFYOIkc/JwIPe3iWl2fP3qN3XP0wTZBq5i \
GlsopYLbgqx0ZVp08o5aljIOsDduPYrJc5aYbxs7l1mxXSxS8qaxe2eg8s/DMiRE \
Bxqunqet+wnWjLEYeCjS832OShF0YUi7nHH2VN4PQjxzxYDxddGYTtcSxHiSAYLA \
X9TW8sWR2WL9bN2ThO7qnN/sq08W1W0FaGy4Vtha4/bm3JKRtfoifrWffxX45MZE \
OGhIutv0PNniufgU5Iej6p+ixNsVDeQPoF9eLiFQ0Mh+AvwtLpg+NVkRiGs8WpYT \
PzAz4bpRnammIU0QEgvyRWuNoA8fE+YDuRBzX0ETyjIXX+E= \
-----END CERTIFICATE-----
```

**Benefits**

In some cases, PEM certificates can be simpler to generate and provision than JKS ones. Generating them doesn't depend on Java's keytool.

**Possible drawbacks**

When configuring `SSL` encryption, `libkafka.sh` will call the `kafka_configure_ssl` more than once. Unfortunately, the `replace_in_file ` function is not compatible with multi-line values, and will be used from the second call to `kafka_configure_ssl` onwards. To solve this I added a variable (`SSL_CONFIGURED`) which keeps track if the SSL settings have already been set in the properties files.

I think a better solution would be to prevent `kafka_configure_ssl` to be called more than once in the first place.

Another solution could be replacing the sed subtitution with a more complex regex (using perl for example) which can accommodate multi-lint strings if needed (e.g. `VALUE="${value}" perl -0777 -i -pe 's/^[#\\s]*'"${key}"'\s*=.*?(?<! \\)$/'"${key}"'=$ENV{VALUE}/gsm' "$file"`).

**Applicable issues**

**Additional information**

[KIP-651](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=158870088)

[Kafka docs](https://kafka.apache.org/documentation/#security_ssl_signing)

2021-01-28 09:12 UTC, juan131 requested changes
Thank so much for this wonderful contribution!

I think this is something that many users will appreciate since generating the JKS files is a pain, and many users resign from configuring TLS due to that. It will also allow us to include more automation in the certificates generation in the [Kafka Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka).

2021-01-28 09:12 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    fi
Please use double `[[` instead of `[` (conventions).

---

I guess you need this to avoid issue with the code below when the key is already set:

```bash
        # Check if the value was set before
        if grep -q "^[#\\s]*$key\s*=.*" "$file"; then
            # Update the existing key
            replace_in_file "$file" "^[#\\s]*${key}\s*=.*" "${key}=${value}" false
        else
            # Add a new key
            printf '\n%s=%s' "$key" "$value" >>"$file"
        fi
```

Is there anyway we can follow a similar approach to the one used for JKS files? I mean, configuring Kafka to read the key and PEM certificate from a file in the filesystem.
Honestly, I don't like the idea of having them in the configuration file.

2021-01-28 17:15 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    fi
I didn't like it either, but I thought that at least the private key had to be set as a variable in the properties files. It turns out this isn't the case.

If you concatenate the public certificate and private key into the same PEM it will load both of them fine from the `ssl.keystore.location` variable. Encrypted private keys are decrypted fine as well.

I'll update the PR.

2021-01-28 19:25 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            print_validation_error "In order to configure the TLS encryption for Kafka you must mount your kafka.keystore.jks (or kafka.key & kefka.pem) and kafka.truststore.jks (or ca-cert) certific
Done

2021-01-28 19:25 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    if [[ -f "$KAFKA_CONF_DIR"/certs/kafka.key && -f "$KAFKA_CONF_DIR"/certs/kafka.pem ]]; then
I've added `KAFKA_CFG_TLS_TYPE` to choose between PEM and JKS file types

2021-01-28 19:29 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    fi
The new version uses locations instead of embedding the files directly. Also, the big if/else blocks have been removed. However, ` ssl.keystore.password` and ` ssl.truststore.password` can only be set when the files are in JKS format, so a small if/else block was added.

2021-01-29 08:27 UTC, juan131 reviewed
Thanks so much!! I prefer this new approach.
Please address a couple of minor suggestions, and we're ready to accept/merger your PR

2021-01-29 08:27 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    ext="$(echo "$KAFKA_CFG_TLS_TYPE" | tr '[:upper:]' '[:lower:]')"
Simpler:
```suggestion
    local -r ext="${KAFKA_CFG_TLS_TYPE,,}"
```
See:
```console
$ foo=BaR
$ echo "${foo,,}"
bar
$ echo "${foo^^}"
BAR
```

2021-01-29 08:27 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    # keystore and truststore passwords are only compatible with JKS files
Should we add a warning in the `kafka_validate` function? Sth like:
```bash
    if [[ "$KAFKA_CFG_TLS_TYPE" = "PEM" ]] && ! is_empty_value "$KAFKA_CERTIFICATE_PASSWORD"; then
        warn "Keystore and truststore passwords are only compatible with JKS, KAFKA_CERTIFICATE_PASSWORD will be ignored."
    fi
```

2021-01-29 08:27 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    fi
great!

2021-01-29 11:40 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    # keystore and truststore passwords are only compatible with JKS files
I don't mind adding a warning, but there would be no way to prevent the warning from appearing when using an encrypted private key inside a PEM file (as KAFKA_CERTIFICATE_PASSWORD is also being used for the `ssl.key.password` configuration). It's harmless, but I think it might be confusing.

Maybe it would be better to separate KAFKA_CERTIFICATE_PASSWORD into two (or three) separate env vars? KAFKA_KEY_PASSWORD and KAFKA_JKS_PASSWORD maybe? Although that would break backwards compatibility...

2021-01-29 11:41 UTC, hugo19941994 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    ext="$(echo "$KAFKA_CFG_TLS_TYPE" | tr '[:upper:]' '[:lower:]')"
Nice. Changed too

2021-01-29 12:36 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    # keystore and truststore passwords are only compatible with JKS files
Nevermind, let's keep it as it's and forget about the warning.

2021-01-29 12:36 UTC, juan131 approved these changes
LGTM

2021-01-29 12:45 UTC, juan131 commented
(sending your PR for internal review, I'll keep you updated)

2021-01-29 15:35 UTC, merged

2021-01-29 15:35 UTC, juan131 commented
PR accepted in internal review, merging your PR!
What's next? A new image revision will be released including your changes. I'll keep you updated once it's released.

2021-01-29 16:45 UTC, juan131 commented
@hugo19941994 we just released the revision `2.7.0-debian-10-r37` including your changes. Please give it a try when you have a chance.

2021-02-01 16:54 UTC, hugo19941994 commented
It works fine on my end. Thanks for taking a look and merging the changes :grinning:.

2021-02-02 08:07 UTC, juan131 commented
Great! Thank you for all the contributions!