#196 - Kafka fails to start when Zookeeper has SASL and SSL enabled
bitnami/bitnami-docker-kafka pull request #199
Opened 2021-11-02 03:07 UTC by Pakkiyarasu

Description of the change

Introduced KAFKA_ZOOKEEPER_TLS_CONFIG_PROPERTIES_FILE envrionment variable.

Modified code to support if Zookeeper is secured with SASL and SSL. I have added --zk-tls-config-file in kafka-configs.sh command if zookeeper protocol is SASL_SSL.

Created new file named zk-tls-config.properties while zookeeper_get_tls_config() method.

Benefits

we can configure Kafka if zookeeper has enbaled SASL authentication and SSL encryption.

Possible drawbacks

Applicable issues

Additional information

2021-11-02 11:14 UTC, alemorcuq requested changes
Thanks for the PR!

2021-11-02 11:14 UTC, alemorcuq commented on 2/debian-10/rootfs/opt/bitnami/scripts/kafka-env.sh
> +    KAFKA_ZOOKEEPER_TLS_TYPE
```suggestion
    KAFKA_ZOOKEEPER_TLS_TYPE
```

2021-11-02 11:14 UTC, alemorcuq commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    export KAFKA_OPTS="$KAFKA_OPTS -Djava.security.auth.login.config=${KAFKA_CONF_DIR}/kafka_jaas.conf"
Why this?

2021-11-02 11:14 UTC, alemorcuq commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            ZOOKEEPER_SSL_CONFIG=$(zookeeper_get_tls_config)
We are not using `ZOOKEEPER_SSL_CONFIG` anywhere, are we?

2021-11-02 11:14 UTC, alemorcuq commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +          -Dzookeeper.ssl.quorum.hostnameVerification=${KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME} \
Why are we adding this new property?

2021-11-02 14:46 UTC, Pakkiyarasu commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    export KAFKA_OPTS="$KAFKA_OPTS -Djava.security.auth.login.config=${KAFKA_CONF_DIR}/kafka_jaas.conf"
I am passing -Dzookeeper.ssl.hostnameVerification=false -Dzookeeper.ssl.quorum.hostnameVerification=false in KAFKA_OPTS during deployment. But this is getting overriden here. That's I added this change.

2021-11-02 14:49 UTC, Pakkiyarasu commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            ZOOKEEPER_SSL_CONFIG=$(zookeeper_get_tls_config)
`Yes we are not. But in zookeeper_get_tls_config() method, I am filling zk-tls-config.properties file. That's why I called this method here. If we don't assign to a variable, SSL settings are getting exposed in the logs. Thats why I assigned to a variable. `

2021-11-02 14:51 UTC, Pakkiyarasu commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +          -Dzookeeper.ssl.quorum.hostnameVerification=${KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME} \
Without this, it was throwing hostname and address mismatch error when kafka tries to connect zookeeper.

2021-11-03 08:04 UTC, juan131 requested changes
Thanks for this great PR! Please check my concerns when you have a chance.

2021-11-03 08:04 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            ZOOKEEPER_SSL_CONFIG=$(zookeeper_get_tls_config)
In the [run.sh](https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/kafka/run.sh#L23), we're appending the output returned by `zookeeper_get_tls_config` to `KAFKA_OPTS`:
```
if [[ "${KAFKA_ZOOKEEPER_PROTOCOL:-}" =~ SSL ]]; then
    ZOOKEEPER_SSL_CONFIG=$(zookeeper_get_tls_config)
    export KAFKA_OPTS="$KAFKA_OPTS $ZOOKEEPER_SSL_CONFIG"
fi
```
Couldn't we do the same here? This way you don't need to create any `zk-tls-config.properties` file.

2021-11-03 16:35 UTC, Pakkiyarasu reviewed
Made changes based on @juan131 comments

2021-11-03 16:37 UTC, Pakkiyarasu commented on 2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            ZOOKEEPER_SSL_CONFIG=$(zookeeper_get_tls_config)
Thanks for your inputs. I made above changes. It works fine. Code is much cleaner now.

2021-11-04 08:47 UTC, juan131 approved these changes
Thanks for applying the suggestions! LGTM
@alemorcuq could you take a look to the new changes too?

2021-11-04 09:15 UTC, alemorcuq approved these changes
Very nice! Thanks!

2021-11-04 09:36 UTC, merged