Configure SSL only for external clients
bitnami/bitnami-docker-kafka pull request #222
Opened 2022-01-28 08:46 UTC by stefan-jonasson

**Description of the change**

Fixes issue https://github.com/bitnami/charts/issues/3539

This patch adds support for using SSL/SASL for external clients
without requiring internal clients to have the same configuration. 

**Benefits**

It's possible to use the helm chart/docker image to automatically configure liseners when configuring the `listenerSecurityProtocolMap` property this: `INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:SSL`

**Possible drawbacks**

The scripts are a bit more complicated.

**Applicable issues**

https://github.com/bitnami/charts/issues/3539

2022-01-28 15:13 UTC, alemorcuq requested changes
Thanks for the PR, @stefan-jonasson ! I'd like @juan131 to review this as well.

2022-01-28 15:13 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +    info "Configuring Kafka for client communications with ${protocol} authentication."
```suggestion
    info "Configuring Kafka for external client communications with ${protocol} authentication."
```

2022-01-28 15:13 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            if [[ ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP:-} =~ EXTERNAL:([a-zA-Z_]*) ]]; then
Do we also need to add a `EXTERNAL` check on the parent `if`?

2022-01-28 15:45 UTC, stefan-jonasson commented on 3/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            if [[ ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP:-} =~ EXTERNAL:([a-zA-Z_]*) ]]; then
You're right. I solved the issue by removing the parent if, it wasn't necessary.

2022-01-31 09:49 UTC, juan131 commented
Hi @stefan-jonasson ! Thanks so much for this contribution!

I'd like to have a little more context about what you're trying to achieve and why can't you achieve it:

- Could you please share the **values.yaml** you're using in your attempt to configure your desired setup?
- Can't you use the parameters `listeners`, `listenerSecurityProtocolMap` and `advertisedListeners` to use any custom configuration for this?

2022-01-31 12:35 UTC, stefan-jonasson commented
Hi @juan131! 

The outcome I try to achieve is to use mTLS for external connections (outside the kubernetes cluster) and PLAINTEXT communication inside the cluster. It's not possible to fix this by specifying the values you suggest. The problem this PR fixes is that the TLS certificates are not added to server.properties when only the EXTERNAL listener was set to use SSL. 


Here is an example of how to use it via the helm chart: 
```
listenerSecurityProtocolMap: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:SSL"
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  tls:
    type: pem
    existingSecrets: 
      - tls-secret
    endpointIdentificationAlgorithm: https
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
```

2022-02-01 07:40 UTC, juan131 commented
I see.. Yes we're assuming that internal and external clients are both configured using the same protocol. Therefore, it's only possible with the current logic to use a different protocol on inter-broker listeners & clients (both internal and external) listeners.

2022-02-01 07:44 UTC, juan131 requested changes
Please check my comments

2022-02-01 07:44 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            kafka_server_conf_set ssl.client.auth "$KAFKA_TLS_CLIENT_AUTH"
This will also enable requesting SSL authentication for internal clients regardless the protocol used in the "INTERNAL" listener, right?

2022-02-01 08:45 UTC, stefan-jonasson commented on 3/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +            kafka_server_conf_set ssl.client.auth "$KAFKA_TLS_CLIENT_AUTH"
No, the ssh.client.auth will only affect the SSL listeners. Client here is not referring to the client listener but the ssl client party.

2022-02-02 07:22 UTC, stefan-jonasson commented
> I see.. Yes we're assuming that internal and external clients are both configured using the same protocol. Therefore, it's only possible with the current logic to use a different protocol on inter-broker listeners & clients (both internal and external) listeners.

Yes, that's what's I try to fix with this change, it's possible to make it work even though it's not a full support for different client protocols.

2022-02-02 07:45 UTC, juan131 approved these changes
LGTM! @stefan-jonasson I wonder if it's worth to slightly modify the example below in the **README.md** so different protocols are used for client/external listeners (making it obvious that's a possibility):

- https://github.com/bitnami/bitnami-docker-kafka#accessing-apache-kafka-with-internal-and-external-clients

2022-02-02 07:51 UTC, stefan-jonasson commented
@juan131 Yes sure, that's a good idea! I'll add it to the PR.

2022-02-02 08:18 UTC, stefan-jonasson commented
@juan131 Changed my mind, while re-writing the docs I think it' would be too complicated to mix SSL aspects together with the external configuration. We need to add several more setting to the external client commands as well, that's probably just make it more confusing. 

For me I would expect it to work with different protocols even though it's not configured with different protocols in the example. It's still two different settings even though they are set to the same value.

2022-02-02 11:24 UTC, alemorcuq approved these changes
Thank you very much!

2022-02-02 12:43 UTC, merged

2022-02-02 12:43 UTC, juan131 commented
Changes merged! I'll update you once a new image including these changes has been published.

2022-02-02 14:06 UTC, juan131 commented
Hi everyone! The new `3.1.0-debian-10-r8` image version includes the changes, see:

- https://github.com/bitnami/bitnami-docker-kafka/commit/e76dc0c7c33a9f1d2dccfee120cab199fb8f47c0