README update to document using Kafka without Zookeeper (KRaft)
bitnami/bitnami-docker-kafka pull request #235
Opened 2022-03-13 23:01 UTC by whithajess

**Description of the change**

Addition to documentation outlining how to use Kafka without Zookeeper (KRaft) 

**Benefits**

Provides configuration for those looking to run Kafka without Zookeeper.

[Benefits of Kafka’s new quorum controller (KRaft):](https://developer.confluent.io/learn/kraft/#benefits-of-kafkas-new-quorum-controller)

- Enables Kafka clusters to scale to millions of partitions through improved control plane performance with the new metadata management
- Improves stability, simplifies the software, and makes it easier to monitor, administer, and support Kafka.
- Allows Kafka to have a single security model for the whole system
- Provides a lightweight, single process way to get started with Kafka
- Makes controller failover near-instantaneous

This is the documented way that Kafka intends to continue to move towards in future versions - [Kafka Improvement Proposal 500 (KIP-500)](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum)

**Possible drawbacks**

Adds confusion to those new to Kafka setting up this Dockerfile for the first time.

**Applicable issues**

#159

**Additional information**

2022-03-16 15:48 UTC, marcosbc requested changes
Thanks for the great PR!

I think it could be worth to actually improve the container logic, to add an environment variable like `KAFKA_ENABLE_KRAFT`. With this environment variable set:

* We could warn users if ZooKeeper connections configurations (`KAFKA_CFG_ZOOKEEPER_CONNECT`) are set in `kafka_validate`.
* We could execute the `kafka-storage.sh` command directly in `kafka_initialize` - although I'm not sure if it's actually required, we would appreciate more info on that command.

That way, instead of having to specifying the `command`, we could simply instruct users to enable Kraft with `KAFKA_ENABLE_KRACT=yes`, and show an example in the README.

What do you think?

2022-03-20 21:43 UTC, whithajess commented
Thanks for looking at this @marcosbc,

I think having an extra variable like `KAFKA_ENABLE_KRAFT` that helps you identify where you go wrong in the configuration would definitely be helpful for the end user in these scenarios.

One of the other things I didn't point out was this part of the config:
```
--cluster-id "lkorDA4qT6W1K_dk0LHvtg"
```
I have just set this to a `random-uuid` as I figure it makes very little difference to the end user but this can be generated using the following taken from [quick start](https://github.com/apache/kafka/tree/trunk/config/kraft#generate-a-cluster-id):
```
./bin/kafka-storage.sh random-uuid
```
Could potentially build this into the `kafka_initialize` executed from the `KAFKA_ENABLE_KRAFT` command.

<hr>

In terms of the storage question:

> We could execute the kafka-storage.sh command directly in kafka_initialize - although I'm not sure if it's actually required, we would appreciate more info on that command.

Unfortunately it is required, hopefully the configuration for **KRaft** becomes easier in the future. 

- [Apache Kafka Documentation around Formatting](https://cwiki.apache.org/confluence/display/KAFKA/KIP-631%3A+The+Quorum-based+Kafka+Controller#KIP631:TheQuorumbasedKafkaController-format)
- [Kafka KRaft Quick Start Documentation](https://github.com/apache/kafka/tree/trunk/config/kraft#format-storage-directories)

The error you get otherwise looks like this:

```No `meta.properties` found in /bitnami/kafka/data (have you run `kafka-storage.sh` to format the directory?)```

2022-03-23 17:06 UTC, marcosbc commented
>Could potentially build this into the `kafka_initialize` executed from the `KAFKA_ENABLE_KRAFT` command.

That would be an option. We would just have to make sure that it doesn't write the info to a file that could be write-protected (e.g. because of being mounted). But as long as KRaft not being the default behavior, it should be fine.

Would you be able to make the changes to support the new environment variable? I think it could be helpful for a lot of people, as we have seen requests to support this feature before.

2022-04-04 01:59 UTC, whithajess commented
@marcosbc Changes made as discussed

2022-04-07 16:42 UTC, marcosbc requested changes
This is looking great! Thanks so much for making the changes! I've requested a few minor requests, could you check them?

2022-04-07 16:42 UTC, marcosbc commented on 2.8/debian-10/rootfs/opt/bitnami/scripts/kafka/setup.sh
> +    elif [[ -z "${KAFKA_ENABLE_KRAFT:-}" ]]; then
Once `KAFKA_ENABLE_KRAFT` is added to [`kafka-env.sh`](https://github.com/bitnami/bitnami-docker-kafka/blob/master/2.8/debian-10/rootfs/opt/bitnami/scripts/kafka-env.sh), we could simply use it like this:

```suggestion
    elif [[ -z "$KAFKA_ENABLE_KRAFT" ]]; then
```

2022-04-07 16:42 UTC, marcosbc commented on 2.8/debian-10/rootfs/opt/bitnami/scripts/kafka/setup.sh
> +if is_boolean_yes "${KAFKA_ENABLE_KRAFT:-}"; then
Same than the above:

```suggestion
if is_boolean_yes "$KAFKA_ENABLE_KRAFT"; then
```

2022-04-07 16:42 UTC, marcosbc commented on 2.8/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +  fi
Minor improvements (also the `export` should not be necessary, since it was already exported in `kafka-env.sh`):

```suggestion
  if [[ -z "$KAFKA_CLUSTER_ID" ]]; then
    warn "KAFKA_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one"
    KAFKA_CLUSTER_ID="$($KAFKA_HOME/bin/kafka-storage.sh random-uuid)"
    debug "Generated Kafka cluster ID '${KAFKA_CLUSTER_ID}'"
  fi
```

2022-04-21 15:42 UTC, marcosbc commented on 2.8/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +kraft_initialize(){
```suggestion
kraft_initialize() {
```

2022-04-21 15:42 UTC, marcosbc commented on 2.8/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh
> +  debug_execute "$KAFKA_HOME/bin/kafka-storage.sh" format --config ${KAFKA_CONF_FILE} --cluster-id ${KAFKA_CLUSTER_ID} --ignore-formatted
Could you fix the indentation for this block as well?

2022-04-21 15:42 UTC, marcosbc commented on 2.8/debian-10/rootfs/opt/bitnami/scripts/kafka/setup.sh
> +  kraft_initialize
```suggestion
    kraft_initialize
```

2022-04-25 08:12 UTC, marcosbc approved these changes
LGTM! Thanks for the great PR!

2022-04-25 10:05 UTC, merged

2022-04-26 00:39 UTC, whithajess commented
@marcosbc Thanks for spending the time to look over this, suggest changes, and code-review it - always a great experience contributing to a receptive open-source library 🙌

2022-05-04 10:43 UTC, mmm8955405 commented
After reading this document, why not add a cluster configuration without zookeeper,

I also need to compare with the official raft



https://github.com/apache/kafka/tree/trunk/raft

2022-05-04 10:50 UTC, carrodher commented
Thanks for the suggestion. Would you like to contribute by creating a PR adding this topology? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.